# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodecache',
            name='is_zero_results',
            field=models.NullBooleanField(help_text='Indicates whether google has returned ZERO_RESULTSfor this address.'),
        ),
    ]
