# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0002_auto_20171126_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodecache',
            name='accessed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='geocodecache',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
